// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyysAX53zlxv0BvWVr1yoUXSvHsK5KQl4',
    appId: '1:86339282228:web:5efc1795875758e4d87161',
    messagingSenderId: '86339282228',
    projectId: 'autorun-897a0',
    authDomain: 'autorun-897a0.firebaseapp.com',
    storageBucket: 'autorun-897a0.appspot.com',
    measurementId: 'G-NTRRMYS4DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTGHl9CvtVEPmj6otOmmH0YPUfeGRtK0',
    appId: '1:86339282228:android:a4f3aa8d4b72bd65d87161',
    messagingSenderId: '86339282228',
    projectId: 'autorun-897a0',
    storageBucket: 'autorun-897a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA47Ikgjb7s6W5HbL8uG4yVmDiZ5s_0WUQ',
    appId: '1:86339282228:ios:b393b9de8470bb7ad87161',
    messagingSenderId: '86339282228',
    projectId: 'autorun-897a0',
    storageBucket: 'autorun-897a0.appspot.com',
    iosClientId: '86339282228-upiph6qghmnl3r0u310nl5jjdfg1h9d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoRun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA47Ikgjb7s6W5HbL8uG4yVmDiZ5s_0WUQ',
    appId: '1:86339282228:ios:b393b9de8470bb7ad87161',
    messagingSenderId: '86339282228',
    projectId: 'autorun-897a0',
    storageBucket: 'autorun-897a0.appspot.com',
    iosClientId: '86339282228-upiph6qghmnl3r0u310nl5jjdfg1h9d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoRun',
  );
}
